<?php

define('TWITTER_CONSUMER_KEY', 'XXXXXXXXXXXXXXXXXXXXXXX');
define('TWITTER_CONSUMER_SECRET', 'XXXXXXXXXXXXXXXXXXXXXXX');
define('TWITTER_ACCESS_KEY', 'XXXXXXXXXXXXXXXXXXXXXXX');
define('TWITTER_ACCESS_SECRET', 'XXXXXXXXXXXXXXXXXXXXXXX'); 

?>
